# Generated by Django 4.1 on 2022-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Enter a book genre (e.g. Science Fiction)", max_length=200
            ),
        ),
    ]
